name: myapp
description: A exported flutter project from FUNCTION12

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  #network
  http:
  dio:
  dartz:

  #state_managment
  flutter_bloc:
  equatable:
  get_it:

  #UI
  flutter_svg:
  lottie:
  modal_bottom_sheet:
  dropdown_button2:

  #storage
  shared_preferences: ^2.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons:
  google_fonts:
  # google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen:
  flutter_gen_runner:
  flutter_launcher_icons:
  shared_preferences_platform_interface:
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_gen:
  integration:
    flutter_svg:

  colors:
    inputs:
      - assets/colors/colors.xml
flutter:
  uses-material-design: true
  assets:
    - assets/page-1/images/
    - assets/svg/
    - assets/png/
  fonts:
    #Poppins
    - family: poppinsBlack
      fonts:
        - asset: assets/fonts/poppins/PoppinsBlack.otf
    - family: poppinsBlackItalic
      fonts:
        - asset: assets/fonts/poppins/PoppinsBlackItalic.otf
    - family: poppinsBold
      fonts:
        - asset: assets/fonts/poppins/PoppinsBold.otf
    - family: poppinsBoldItalic
      fonts:
        - asset: assets/fonts/poppins/PoppinsBoldItalic.otf
    - family: poppinsExtraBoldItalic
      fonts:
        - asset: assets/fonts/poppins/PoppinsExtraBoldItalic.otf
    - family: poppinsExtraLight
      fonts:
        - asset: assets/fonts/poppins/PoppinsExtraLight.otf
    - family: poppinsExtraLightItalic
      fonts:
        - asset: assets/fonts/poppins/PoppinsExtraLightItalic.otf
    - family: poppinsItalic
      fonts:
        - asset: assets/fonts/poppins/PoppinsItalic.otf
    - family: poppinsLight
      fonts:
        - asset: assets/fonts/poppins/PoppinsLight.otf
    - family: poppinsLightItalic
      fonts:
        - asset: assets/fonts/poppins/PoppinsLightItalic.otf
    - family: poppinsMedium
      fonts:
        - asset: assets/fonts/poppins/PoppinsMedium.otf
    - family: poppinsMediumItalic
      fonts:
        - asset: assets/fonts/poppins/PoppinsMediumItalic.otf
    - family: poppinsRegular
      fonts:
        - asset: assets/fonts/poppins/PoppinsRegular.otf
    - family: poppinsSemiBold
      fonts:
        - asset: assets/fonts/poppins/PoppinsSemiBold.otf
    - family: poppinsSemiBoldItalic
      fonts:
        - asset: assets/fonts/poppins/PoppinsSemiBoldItalic.otf
    - family: poppinsThin
      fonts:
        - asset: assets/fonts/poppins/PoppinsThin.otf
    - family: poppinsThinItalic
      fonts:
        - asset: assets/fonts/poppins/PoppinsThinItalic.otf
    # Quincy CF
    - family: connaryFagenQuincyCFText
      fonts:
        - asset: assets/fonts/quincy_cf/ConnaryFagenQuincyCFText.otf
    - family: connaryFagenQuincyCFTextItalic
      fonts:
        - asset: assets/fonts/quincy_cf/ConnaryFagenQuincyCFTextItalic.otf
    - family: connaryFagenQuincyCFThin
      fonts:
        - asset: assets/fonts/quincy_cf/ConnaryFagenQuincyCFThin.otf
    - family: ConnaryFagenQuincyCFThinItalic
      fonts:
        - asset: assets/fonts/quincy_cf/ConnaryFagenQuincyCFThinItalic.otf
    - family: quincyCFBlack
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFBlack.ttf
    - family: quincyCFBlackItalic
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFBlackItalic.ttf
    - family: quincyCFBold
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFBold.ttf
    - family: quincyCFBoldItalic
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFBoldItalic.ttf
    - family: quincyCFExtraBold
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFExtraBold.ttf
    - family: quincyCFExtraBoldItalic
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFExtraBoldItalic.ttf
    - family: quincyCFLight
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFLight.ttf
    - family: quincyCFLightItalic
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFLightItalic.ttf
    - family: quincyCFMedium
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFMedium.ttf
    - family: quincyCFMediumItalic
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFMediumItalic.ttf
    - family: quincyCFRegular
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFRegular.ttf
    - family: quincyCFRegularItalic
      fonts:
        - asset: assets/fonts/quincy_cf/QuincyCFRegularItalic.ttf